# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urls.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urls.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nurls.proto\x12\x0e\x65ncurtador_url\"\'\n\x12\x45ncurtarUrlRequest\x12\x11\n\turl_longa\x18\x01 \x01(\t\"K\n\x13\x45ncurtarUrlResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x11\n\turl_curta\x18\x02 \x01(\t\x12\x10\n\x08msg_erro\x18\x03 \x01(\t\",\n\x14ObterUrlLongaRequest\x12\x14\n\x0c\x63odigo_curto\x18\x01 \x01(\t\"M\n\x15ObterUrlLongaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x11\n\turl_longa\x18\x02 \x01(\t\x12\x10\n\x08msg_erro\x18\x03 \x01(\t2\xc9\x01\n\rEncurtadorURL\x12X\n\x0b\x45ncurtarURL\x12\".encurtador_url.EncurtarUrlRequest\x1a#.encurtador_url.EncurtarUrlResponse\"\x00\x12^\n\rObterURLLonga\x12$.encurtador_url.ObterUrlLongaRequest\x1a%.encurtador_url.ObterUrlLongaResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urls_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCURTARURLREQUEST']._serialized_start=30
  _globals['_ENCURTARURLREQUEST']._serialized_end=69
  _globals['_ENCURTARURLRESPONSE']._serialized_start=71
  _globals['_ENCURTARURLRESPONSE']._serialized_end=146
  _globals['_OBTERURLLONGAREQUEST']._serialized_start=148
  _globals['_OBTERURLLONGAREQUEST']._serialized_end=192
  _globals['_OBTERURLLONGARESPONSE']._serialized_start=194
  _globals['_OBTERURLLONGARESPONSE']._serialized_end=271
  _globals['_ENCURTADORURL']._serialized_start=274
  _globals['_ENCURTADORURL']._serialized_end=475
# @@protoc_insertion_point(module_scope)
