# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import urls_pb2 as urls__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in urls_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncurtadorURLStub(object):
    """Definição do serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncurtarURL = channel.unary_unary(
                '/encurtador_url.EncurtadorURL/EncurtarURL',
                request_serializer=urls__pb2.EncurtarUrlRequest.SerializeToString,
                response_deserializer=urls__pb2.EncurtarUrlResponse.FromString,
                _registered_method=True)
        self.ObterURLLonga = channel.unary_unary(
                '/encurtador_url.EncurtadorURL/ObterURLLonga',
                request_serializer=urls__pb2.ObterUrlLongaRequest.SerializeToString,
                response_deserializer=urls__pb2.ObterUrlLongaResponse.FromString,
                _registered_method=True)


class EncurtadorURLServicer(object):
    """Definição do serviço
    """

    def EncurtarURL(self, request, context):
        """RPC para encurtar uma URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterURLLonga(self, request, context):
        """RPC para obter a URL longa original
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncurtadorURLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncurtarURL': grpc.unary_unary_rpc_method_handler(
                    servicer.EncurtarURL,
                    request_deserializer=urls__pb2.EncurtarUrlRequest.FromString,
                    response_serializer=urls__pb2.EncurtarUrlResponse.SerializeToString,
            ),
            'ObterURLLonga': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterURLLonga,
                    request_deserializer=urls__pb2.ObterUrlLongaRequest.FromString,
                    response_serializer=urls__pb2.ObterUrlLongaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encurtador_url.EncurtadorURL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('encurtador_url.EncurtadorURL', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncurtadorURL(object):
    """Definição do serviço
    """

    @staticmethod
    def EncurtarURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encurtador_url.EncurtadorURL/EncurtarURL',
            urls__pb2.EncurtarUrlRequest.SerializeToString,
            urls__pb2.EncurtarUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterURLLonga(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encurtador_url.EncurtadorURL/ObterURLLonga',
            urls__pb2.ObterUrlLongaRequest.SerializeToString,
            urls__pb2.ObterUrlLongaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
